"""CP-94: what round three found in estate.py — `status` on a run that has
not died, the sandbox image checked before any Docker call, the pull
heartbeat, the pins in force naming their empty sets, and the help text a
foreign model forces you to read.

Hermetic — no Docker daemon, no estate. Where a docker binary is needed the
tests put a recording fake on PATH that answers only what the code under
test may ask (the CP-92 canary pattern)."""

from __future__ import annotations

import fcntl
import importlib.util
import json
import os
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from types import SimpleNamespace

import pytest

from conftest import FakePull

ESTATE_DIR = Path(__file__).resolve().parents[2]
ESTATE_PY = ESTATE_DIR / "estate.py"
STAGING = ESTATE_DIR / "corpus" / "staging"
HARNESS = "ghcr.io/mhganainy/gsj-pi-harness:pi0.83.0-3"
REFUSAL_CURE = (f"docker pull {HARNESS}   (a plain pull: the published tag is a two-platform "
                "index since CP-64 and resolves this daemon's native platform; if — and only "
                "if — that pull answers `no matching manifest for linux/<arch>`, pull again "
                "with --platform linux/amd64 and the sandbox runs under emulation) — or load "
                "it out-of-band (docker save | docker load); --skip-sandbox-image records the "
                "absence and continues")


@pytest.fixture
def est(tmp_path, monkeypatch):
    spec = importlib.util.spec_from_file_location("estate_cp94", ESTATE_PY)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    monkeypatch.setattr(module, "RUNS", tmp_path)
    return module


def fake_docker(scratch: Path, script: str) -> dict:
    """A `docker` on PATH that records every call and runs `script` (sh) with
    the call in $*; the environment to run estate.py under."""
    fake_bin = scratch / "bin"
    fake_bin.mkdir(parents=True, exist_ok=True)
    calls = scratch / "docker-calls"
    docker = fake_bin / "docker"
    docker.write_text('#!/bin/sh\nprintf "%s\\n" "$*" >> "$CP94_DOCKER_CALLS"\n' + script)
    docker.chmod(0o700)
    env = dict(os.environ, PATH=str(fake_bin) + os.pathsep + os.environ.get("PATH", ""),
               CP94_DOCKER_CALLS=str(calls), PYTHONDONTWRITEBYTECODE="1")
    env.pop("GSJ_PINS_PATH", None)
    return {"env": env, "calls": calls}


def invoke(runs: Path, *args: str, docker: dict | None = None) -> subprocess.CompletedProcess:
    if docker is None:
        docker = fake_docker(runs / ".fake", 'exit 97\n')
    proc = subprocess.run([sys.executable, str(ESTATE_PY), *args, "--runs-dir", str(runs)],
                          env=docker["env"], capture_output=True, text=True, timeout=120)
    return proc


def partial_record(corpus: str) -> dict:
    return {"schema": 1, "run": "canary", "run_dir": "/disposable/canary",
            "corpus": {"path": corpus, "name": "my-corpus", "owner": "my-owner",
                       "case_ids": ["case_0001"]},
            "forgejo": {"mode": "created", "url": "http://127.0.0.1:9",
                        "container_url": "http://gsj-canary-forgejo:3000",
                        "admin_user": "gsj-admin", "admin_credential_env": "X",
                        "require_signin_view": True},
            "compose": {"mcp": {"image": "registry.invalid/gsj-mcp-service:9",
                                "container": "gsj-canary-mcp", "port": 8790,
                                "data": "/d", "config": "/c", "read_env": "R"}},
            "secrets": {"names": []}}


def partial_run(runs: Path, *, compose_yaml: bool = False) -> Path:
    rd = runs / "canary"
    rd.mkdir(parents=True)
    corpus = runs / "corpus"
    corpus.mkdir()
    (rd / "run.json").write_text(json.dumps(partial_record(str(corpus))))
    (rd / ".env").write_text("")
    if compose_yaml:
        (rd / "compose.yaml").write_text("# GENERATED by estate.py for run canary\n")
    return rd


# ------------------------------------------------ status: three states, not two

def hold_lock(runs: Path, name: str):
    """What `up` does for its whole command: an exclusive kernel lock on
    <runs>/.locks/<name>.lock (a separate open file description, so the
    subprocess's non-blocking probe sees it held)."""
    locks = runs / ".locks"
    locks.mkdir(exist_ok=True, mode=0o700)
    handle = open(locks / f"{name}.lock", "w")
    fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
    return handle


def test_status_says_active_and_wait_while_up_holds_the_lock(tmp_path):
    """Two strangers ran `status` mid-`up` and were told the run had died
    (b1) or that nothing was running (a1, the demo): a held lock is a run
    in flight — say so, say wait, recommend nothing."""
    partial_run(tmp_path)
    handle = hold_lock(tmp_path, "canary")
    try:
        proc = invoke(tmp_path, "status", "--name", "canary")
    finally:
        fcntl.flock(handle, fcntl.LOCK_UN)
        handle.close()
    assert proc.returncode == 0, proc.stderr
    out = proc.stdout
    assert "== run canary ==" in out and "ACTIVE" in out and "still running" in out
    assert "is ACTIVE — wait for the running command" in out
    assert "Do not start a second `up`" in out and "never delete the lock file" in out
    # the phases that stand are still reported — the same rows as the incomplete report
    assert "corpus    my-corpus: 1 case(s); owner 'my-owner'" in out
    # an active run has not died: what it has not reached, it has not reached YET
    assert "mcp       not reached yet — up is in or before this phase" in out
    assert "taskbank  not reached yet" in out and "engine    not recorded yet" in out
    assert "config    not written yet" in out and "died" not in out
    # and none of the incomplete report's verdicts: no refusal, no resume cure
    assert "REFUSED" not in proc.stderr and "incomplete" not in out
    assert "to resume" not in out and "to resume" not in proc.stderr
    assert "Traceback" not in proc.stderr


def test_status_on_a_locked_run_with_no_record_yet_names_the_first_phase(tmp_path):
    """During `up`'s first phase there is no run.json (it lands once Forgejo
    stands): a held lock still means active, never `no run named`."""
    (tmp_path / "canary").mkdir()
    handle = hold_lock(tmp_path, "canary")
    try:
        proc = invoke(tmp_path, "status", "--name", "canary")
    finally:
        fcntl.flock(handle, fcntl.LOCK_UN)
        handle.close()
    assert proc.returncode == 0, proc.stderr
    assert "ACTIVE" in proc.stdout and "no record yet" in proc.stdout
    assert "first phase" in proc.stdout and "no run named" not in proc.stderr


def test_status_with_the_lock_free_still_reports_incomplete_and_refuses(tmp_path):
    """The lock file exists (every `up` creates it) but nothing holds it:
    CP-92's incomplete report, exit 1, the resume cure — unchanged."""
    partial_run(tmp_path)
    locks = tmp_path / ".locks"
    locks.mkdir()
    (locks / "canary.lock").write_text("")
    proc = invoke(tmp_path, "status", "--name", "canary")
    assert proc.returncode == 1
    assert "incomplete — up did not finish" in proc.stdout and "ACTIVE" not in proc.stdout
    assert "REFUSED" in proc.stderr and "to resume" in proc.stderr


def test_lock_held_reads_a_missing_lock_as_not_in_flight(est, tmp_path):
    r = est.Run("never-run")
    assert est.lock_held(r) is False
    handle = hold_lock(tmp_path, "never-run")
    try:
        assert est.lock_held(r) is True
    finally:
        fcntl.flock(handle, fcntl.LOCK_UN)
        handle.close()
    assert est.lock_held(r) is False


def test_status_incomplete_asks_the_daemon_about_a_container_the_record_has_not_caught_up_with(
        est, monkeypatch, capsys, tmp_path):
    """The stranger's `mcp not reached` two lines above `gsj-strangerb-mcp Up
    About a minute`: the record's mcp block lands after ingest, the compose
    block and the container before the embed — the row must say what the
    daemon says."""
    partial_run(tmp_path, compose_yaml=True)
    # docker's `table` format, as it really prints: space-padded columns, no tabs
    ps = subprocess.CompletedProcess([], 0, "NAME                 STATUS\ngsj-canary-forgejo   Up 40 minutes\n"
                                            "gsj-canary-mcp       Up About a minute\n", "")
    monkeypatch.setattr(est, "compose", lambda rundir, *a, **k: ps)

    def fake_http(method, url, body=None, **kw):
        if url == "http://127.0.0.1:8790/health":
            return 200, {"state": "ready"}
        return None, "ConnectionRefusedError"

    monkeypatch.setattr(est, "http", fake_http)
    with pytest.raises(SystemExit) as exc:
        est.cmd_status(SimpleNamespace(name="canary"))
    assert exc.value.code == 1
    out = capsys.readouterr().out
    assert ("mcp       created http://127.0.0.1:8790  state=ready  container Up About a minute "
            "— reached (the record's mcp block lands after ingest; a resume adopts what stands)") in out
    assert "not reached" not in out.split("mcp       ")[1].split("\n")[0]
    assert "engine    not recorded — probed after verify" in out
    assert "config    not written" in out


def test_status_incomplete_keeps_not_reached_when_the_daemon_holds_no_such_container(
        est, monkeypatch, capsys, tmp_path):
    partial_run(tmp_path, compose_yaml=True)
    ps = subprocess.CompletedProcess([], 0, "NAME                 STATUS\ngsj-canary-forgejo   Up 40 minutes\n", "")
    monkeypatch.setattr(est, "compose", lambda rundir, *a, **k: ps)
    monkeypatch.setattr(est, "http", lambda *a, **k: (None, "ConnectionRefusedError"))
    with pytest.raises(SystemExit):
        est.cmd_status(SimpleNamespace(name="canary"))
    out = capsys.readouterr().out
    assert ("mcp       not reached — up died in or before this phase "
            "(retrieval service image registry.invalid/gsj-mcp-service:9)") in out


# ------------------------------------------ the sandbox image, checked FIRST

def test_up_refuses_an_absent_sandbox_image_before_any_container_is_pulled_or_created(tmp_path):
    """A stranger's `up` ran 41 minutes of pipeline — Forgejo, owner, tokens,
    repos, a 1.28 GiB pull, an index — and then met this refusal for an
    image whose name it had printed at +0.0s. The check sits with the
    preflight now: the only Docker calls before the refusal are the daemon
    probe and the image inspection, and the refusal text is CP-92's."""
    if not STAGING.is_dir():
        pytest.skip("the checkout's staging corpus is the default --corpus")
    docker = fake_docker(tmp_path / ".fake",
                         'case "$1 $2" in\n'
                         '  "info --format") echo 29.0.0; exit 0 ;;\n'
                         '  "image inspect") echo "No such image" >&2; exit 1 ;;\n'
                         'esac\necho "unexpected docker call: $*" >&2; exit 97\n')
    proc = invoke(tmp_path, "up", "-y", "--name", "canary", "--corpus", str(STAGING),
                  docker=docker)
    assert proc.returncode == 1, proc.stdout + proc.stderr
    err = proc.stderr
    assert f"REFUSED — the sandbox image {HARNESS} is not present on this daemon." in err
    assert "found:    docker image inspect failed (or no docker here)" in err
    assert f"what to do: {REFUSAL_CURE}" in err
    assert "Traceback" not in err
    calls = docker["calls"].read_text().splitlines()
    assert calls == ["info --format {{.ServerVersion}} {{.Driver}}", f"image inspect {HARNESS}"], calls   # CP-96: the driver rides the same call
    # nothing was pulled, composed, created or probed — and no run record landed
    assert not any(c.split()[0] in ("pull", "compose", "network", "run") for c in calls)
    assert not (tmp_path / "canary" / "run.json").exists()
    assert "forgejo" not in proc.stdout.lower().split("sandbox")[0] or "docker compose up" not in proc.stdout


def test_up_names_a_stopped_daemon_as_such_not_as_a_missing_image(tmp_path):
    if not STAGING.is_dir():
        pytest.skip("the checkout's staging corpus is the default --corpus")
    docker = fake_docker(tmp_path / ".fake",
                         'echo "Cannot connect to the Docker daemon" >&2; exit 1\n')
    proc = invoke(tmp_path, "up", "-y", "--name", "canary", "--corpus", str(STAGING),
                  docker=docker)
    assert proc.returncode == 1
    assert "the Docker daemon is not reachable" in proc.stderr
    assert "sandbox image" not in proc.stderr
    assert docker["calls"].read_text().splitlines() == ["info --format {{.ServerVersion}} {{.Driver}}"]


def test_skip_sandbox_image_records_the_absence_and_goes_on_to_the_next_docker_call(tmp_path):
    """--skip-sandbox-image: no refusal at the preflight; the next Docker
    call is the Forgejo create's own (check_docker's compose probe)."""
    if not STAGING.is_dir():
        pytest.skip("the checkout's staging corpus is the default --corpus")
    docker = fake_docker(tmp_path / ".fake",
                         'case "$1 $2" in\n'
                         '  "info --format") echo 29.0.0; exit 0 ;;\n'
                         '  "image inspect") exit 1 ;;\n'
                         '  "compose version") echo "no compose here" >&2; exit 1 ;;\n'
                         'esac\necho "unexpected docker call: $*" >&2; exit 97\n')
    proc = invoke(tmp_path, "up", "-y", "--name", "canary", "--corpus", str(STAGING),
                  "--skip-sandbox-image", docker=docker)
    assert proc.returncode == 1
    assert "sandbox image" not in proc.stderr
    assert "`docker compose` (v2 plugin) is missing" in proc.stderr
    calls = docker["calls"].read_text().splitlines()
    assert calls[:2] == [f"image inspect {HARNESS}", "info --format {{.ServerVersion}} {{.Driver}}"]


# ------------------------------------------------------- the pull heartbeat

def test_image_pull_prints_a_heartbeat_with_elapsed_and_host_bytes_while_the_pull_runs(
        est, monkeypatch, capsys):
    """21 minutes of silence on a healthy pull (a2), 39 (b2): once a
    heartbeat interval the tool says how long, and whether the host's pipe
    moved — through the `run` seam, so a fake pull is enough."""
    monkeypatch.setattr(est, "PULL_HEARTBEAT_S", 0.15)
    counter = {"rx": 1_000_000}

    def rx():
        counter["rx"] += 3 * 1024 * 1024
        return counter["rx"]

    monkeypatch.setattr(est, "host_rx_bytes", rx)

    def fake_popen(cmd, **kw):
        assert cmd == ["docker", "pull", "example.invalid/big:1"]
        assert kw.get("stdout") is subprocess.PIPE and kw.get("stderr") is subprocess.PIPE
        return FakePull(cmd, 0, delay=0.5)

    monkeypatch.setattr(est, "popen", fake_popen)      # CP-96: the streaming seam
    proc = est.image_pull("example.invalid/big:1", "mcp")
    assert proc.returncode == 0
    out = capsys.readouterr().out
    beats = [line for line in out.splitlines() if "still pulling example.invalid/big:1" in line]
    assert len(beats) >= 2, out
    assert all("elapsed" in b and "this host received 3.0 MiB" in b and "the pipe is moving" in b
               for b in beats), beats
    assert "a heartbeat every 0s says which phase the layers are in" in out


def test_image_pull_heartbeat_says_nothing_moved_and_names_the_three_checks(est, monkeypatch, capsys):
    monkeypatch.setattr(est, "PULL_HEARTBEAT_S", 0.15)
    monkeypatch.setattr(est, "host_rx_bytes", lambda: 42)
    monkeypatch.setattr(est, "popen", lambda cmd, **kw: FakePull(cmd, 1, stderr="boom", delay=0.4))
    proc = est.image_pull("example.invalid/big:1", "forgejo")
    assert proc.returncode == 1 and proc.stderr == "boom"
    out = capsys.readouterr().out
    assert "received NOTHING" in out and "troubleshooting.md, the pull row" in out


def test_image_pull_without_readable_counters_still_beats(est, monkeypatch, capsys):
    monkeypatch.setattr(est, "PULL_HEARTBEAT_S", 0.15)
    monkeypatch.setattr(est, "host_rx_bytes", lambda: None)
    monkeypatch.setattr(est, "popen", lambda cmd, **kw: FakePull(cmd, 0, delay=0.4))
    est.image_pull("example.invalid/big:1", "mcp")
    out = capsys.readouterr().out
    assert "byte counters are not readable here" in out


def test_image_pull_returns_at_once_for_a_fast_pull_with_no_heartbeat(est, monkeypatch, capsys):
    monkeypatch.setattr(est, "popen", lambda cmd, **kw: FakePull(cmd, 0))
    proc = est.image_pull("example.invalid/small:1", "mcp")
    assert proc.returncode == 0
    assert "still pulling" not in capsys.readouterr().out


def test_host_rx_bytes_is_a_count_or_none_and_never_raises(est):
    value = est.host_rx_bytes()
    assert value is None or (isinstance(value, int) and value >= 0)


# --------------------------------------------- the pins in force: empty sets

def test_pins_check_names_the_approved_sets_left_empty(est, monkeypatch, tmp_path):
    """A foreign model's G4 slots are EMPTY on purpose; `up` must say that
    nothing checks them, not let the pins line read as all green."""
    if not STAGING.is_dir():
        pytest.skip("the checkout's staging corpus")
    import gsj_rollout.checks as checks
    packaged = json.loads(Path(checks.PINS_PATH).read_text())
    packaged["pins"]["tokenizer_hash"] = []
    packaged["pins"]["chat_template_hash"] = []
    pins = tmp_path / "pins.gsj.json"
    pins.write_text(json.dumps(packaged))
    monkeypatch.setattr(checks, "PINS_PATH", pins)
    monkeypatch.setenv("GSJ_PINS_PATH", str(pins))
    corpus = est.load_corpus(STAGING, None, HARNESS)
    g1 = est.pins_g1_check(corpus)
    assert g1["checked"] and g1["pins_source"] == "GSJ_PINS_PATH"
    assert g1["empty_sets"] == ["chat_template_hash", "tokenizer_hash"]
    assert g1["not_in_approved_set"] == []


def test_pins_check_reports_no_empty_sets_for_the_packaged_reference(est):
    if not STAGING.is_dir():
        pytest.skip("the checkout's staging corpus")
    corpus = est.load_corpus(STAGING, None, HARNESS)
    g1 = est.pins_g1_check(corpus)
    assert g1["checked"] and g1["empty_sets"] == []


# --------------------------------------------------------------- help text

def test_up_help_explains_the_flags_a_foreign_model_forces_you_to_set():
    proc = subprocess.run([sys.executable, str(ESTATE_PY), "up", "--help"],
                          capture_output=True, text=True, timeout=60)
    assert proc.returncode == 0
    text = " ".join(proc.stdout.split())
    for flag, fragment in (("--end-of-turn-token-id", "bring-your-own.md#your-model"),
                           ("--context-window", "must not exceed the endpoint's max_model_len"),
                           ("--max-tokens", "per-turn generation budget"),
                           ("--gateway-host", "explicit skips the probe"),
                           ("--runs-dir", "an EXISTING writable directory")):
        assert flag in text and fragment in text, (flag, fragment)


def test_status_help_and_docstring_name_the_three_states():
    proc = subprocess.run([sys.executable, str(ESTATE_PY), "--help"],
                          capture_output=True, text=True, timeout=60)
    assert proc.returncode == 0
    text = " ".join(proc.stdout.split())
    assert "a held lock means an `up`, `update` or `down` is still running" in text
    assert "the sandbox image is checked before anything is pulled or created" in text


# ------------------------------------- the page's probe_model.py, step 5

PAGE = ESTATE_DIR.parent / "docs" / "guide" / "bring-your-own.md"
VLLM_400 = ('{"object":"error","message":"\\"auto\\" tool choice requires --enable-auto-tool-choice '
            'and --tool-call-parser to be set","type":"BadRequestError","param":null,"code":400}')


def page_scripts() -> list[str]:
    import re
    if not PAGE.is_file():
        pytest.skip("docs/guide/bring-your-own.md is not in this tree")
    blocks = re.findall(r"```python\n(.*?)```", PAGE.read_text(), re.S)
    assert "bring-your-own.md#your-model" in blocks[0]
    return blocks


class FakeEngine:
    """A vLLM-shaped OpenAI endpoint on a loopback port: /v1/models, the
    messages form of /tokenize, and /v1/chat/completions either served WITH
    the tool flags (200 + logprobs) or WITHOUT (vLLM's 400 body)."""

    def __init__(self, *, tool_flags: bool):
        import http.server
        import threading
        marker = [151645]
        base = [151644, 872, 198, 9707, 13, 151645, 198]              # <|im_start|>user\nHello.<|im_end|>\n
        tail = [151644, 77091, 198, 151667, 271, 151668, 271]         # the generation prompt

        class Handler(http.server.BaseHTTPRequestHandler):
            def log_message(self, *a):  # quiet
                pass

            def _send(self, code, body):
                data = json.dumps(body).encode()
                self.send_response(code)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)

            def do_GET(self):
                assert self.path == "/v1/models"
                self._send(200, {"data": [{"id": "fake-model", "max_model_len": 4096}]})

            def do_POST(self):
                payload = json.loads(self.rfile.read(int(self.headers["Content-Length"])))
                if self.path == "/tokenize":
                    if "prompt" in payload:
                        return self._send(200, {"tokens": marker})
                    msgs = payload["messages"]
                    ids = list(base) + (list(base) if len(msgs) > 1 else [])
                    if payload.get("add_generation_prompt"):
                        ids += tail
                    return self._send(200, {"tokens": ids})
                assert self.path == "/v1/chat/completions"
                if payload.get("tool_choice") == "auto" and not tool_flags:
                    return self._send(400, json.loads(VLLM_400))
                return self._send(200, {"choices": [{"finish_reason": "stop",
                                                     "message": {"role": "assistant", "content": "OK."},
                                                     "logprobs": {"content": [{"token": "OK", "logprob": -0.01}]}}]})

        self.server = http.server.HTTPServer(("127.0.0.1", 0), Handler)
        self.url = f"http://127.0.0.1:{self.server.server_port}"
        threading.Thread(target=self.server.serve_forever, daemon=True).start()

    def close(self):
        self.server.shutdown()


def run_probe(tmp_path: Path, engine: FakeEngine) -> subprocess.CompletedProcess:
    script = tmp_path / "probe_model.py"
    script.write_text(page_scripts()[0])
    return subprocess.run([sys.executable, str(script)], cwd=tmp_path, capture_output=True, text=True,
                          env={**os.environ, "ENGINE": engine.url}, timeout=60)


def test_probe_step_5_passes_on_an_engine_served_with_the_tool_flags(tmp_path):
    engine = FakeEngine(tool_flags=True)
    try:
        proc = run_probe(tmp_path, engine)
    finally:
        engine.close()
    assert proc.returncode == 0, proc.stderr
    assert "episode probe         tool_choice=auto accepted, logprobs present (1 tokens)" in proc.stdout
    written = json.loads((tmp_path / "model-probe.json").read_text())
    probe = written["requests"]["episode_probe"]["request"]
    assert probe["tool_choice"] == "auto" and probe["logprobs"] is True and probe["max_tokens"] == 16
    assert probe["chat_template_kwargs"] == {"enable_thinking": False, "preserve_thinking": True}
    assert probe["tools"][0]["function"]["name"] == "ping"
    assert "tool-call parser IDENTITY (a serve flag; its presence was probed in step 5)" in \
        written["derived"]["not_measured"]


def test_probe_step_5_stops_on_an_engine_served_without_the_flags_and_quotes_the_400(tmp_path):
    """The stranger's reasoning: HTTP 400 here means every episode will ERROR
    and only the engine's operator can fix it — say so before an episode is
    spent, with vLLM's own body so the reader recognises it."""
    engine = FakeEngine(tool_flags=False)
    try:
        proc = run_probe(tmp_path, engine)
    finally:
        engine.close()
    assert proc.returncode == 1
    assert "chat completion with tool_choice=auto -> HTTP 400:" in proc.stderr
    assert 'tool choice requires --enable-auto-tool-choice and --tool-call-parser to be set' in proc.stderr
    assert "cannot run an episode as served; its operator must add the two flags" in proc.stderr
    assert "Traceback" not in proc.stderr
    assert not (tmp_path / "model-probe.json").exists()          # it stopped before writing
    # steps 1–4 had passed: the derived values were printed before step 5 refused? No —
    # the script asserts before it derives and prints at the end; nothing else is claimed.
    assert "written" not in proc.stdout


def test_the_page_says_the_pins_file_covers_and_the_borrowed_endpoint():
    text = PAGE.read_text()
    for anchor in ("## What an acceptance covers", "## The borrowed endpoint",
                   "| `tokenizer_hash` | G4 |", "sound for **provenance work**",
                   "not for training-distribution work"):
        assert anchor in text, anchor
    # the derive script writes the same coverage vocabulary the demo's bootstrap writes
    assert '"coverage": {' in page_scripts()[1] and '"sampling_policy": "UNKNOWN' in page_scripts()[1]
